source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'thin'
gem 'react-rails-hot-loader', path: '../../'

group :development, :test do
  gem 'spring'
end
